### ISSUE TITLE
Why does the error "in <module>     graph_true=pickle.load(open("./data/bnlearn_mildew_graph.pkl", "rb"), encoding='utf-8')   File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\networkx\classes\reportviews.py", line 994, in __setstate__     self._adjdict = G._succ if hasattr(G, "succ") else G._adj AttributeError: 'DiGraph' object has no attribute '_adj'" appear

### ISSUE THREAD

**Issue by zys07** [acmi-lab/local-causal-discovery#1]

**Comment by zys07** [comment]
What version is your networkx？

**Comment by shantanu95** [comment]
hey, my networkx version is '2.8.5'. i am able to load the graph successfully with this version.

**Comment by zys07** [comment]
ok thanks Maybe my version is wrong

**Comment by zys07** [comment]
> hey, my networkx version is '2.8.5'. i am able to load the graph successfully with this version.

Sorry to disturb you, but I was recently reading your article "Local Causal Discovery for Estimating Causal Effects", and I would like to ask about the experimental part of the article regarding the processing of discrete data such as alarm and magic-niab datasets. niab dataset, could you please give me your email and other contact information? Thank you.

**Comment by shantanu95** [comment]
Sure, no problem. My email is shantang@andrew.cmu.edu.
